const FoodData = {
    "Apple Core": { "img": "Apple-Core.gif" },
    "Half a Donut": { "img": "Half-a-Donut.gif" },
    "Piece of Bread": { "img": "Piece-of-Bread.gif" },
    "Can of Coke": { "img": "Can-of-Coke.gif" },
    "Piece of Pizza": { "img": "Piece-of-Pizza.gif" },
    "Meat Pie": { "img": "Meat-Pie.gif" },
    "Can of Pepsi": { "img": "Can-of-Pepsi.gif" },
    "Rotten Fish": { "img": "Rotten-Fish.gif" },
    "Half Eaten Burger": { "img": "Half-Eaten-Burger.gif" },
    "Packet of Fries": { "img": "Packet-of-Fries.gif" },
    "New Pizza": { "img": "New-Pizza.gif" },
    "Chewed Chicken Leg": { "img": "Chewed-Chicken-Leg.gif" },
    "Raw Chicken Leg": { "img": "Raw-Chicken-Leg.gif" },
    "Cooked Chicken": { "img": "Cooked-Chicken.gif" },
    "Half a HotDog": { "img": "Half-a-HotDog.gif" },
    "HotDog": { "img": "HotDog.gif" },
    "KFC Meal": { "img": "KFC-Meal.gif" },
    "Raw Potato": { "img": "Raw-Potato.gif" },
    "Vanilla Ice Cream": { "img": "Vanilla-Ice-Cream.gif" },
    "Chocolate Ice Cream": { "img": "Chocolate-Ice-Cream.gif" },
    "Fresh Apple": { "img": "Fresh-Apple.gif" },
    "Fighters Lunch": { "img": "Fighters-Lunch.gif" },
    "Double-Double": { "img": "Double-Double.gif" },
    "Bachelor Chow": { "img": "Bachelor-Chow.gif" },
    "Smart Bread": { "img": "Smart-Bread.gif" },
    "Day Old Coffee Naan": { "img": "Day-Old-Coffee-Naan.gif" },
    "Half a Sandwich Naan": { "img": "Half-a-Sandwich-Naan.gif" },
    "Discarded Taco Naan": { "img": "Discarded-Taco-Naan.gif" },
    "Wonka Bar": { "img": "Wonka-Bar.gif" },
    "Single-Single": { "img": "Single-Single.gif" },
    "Wonka-stripe Candy Cane": { "img": "Wonka-stripe-Candy-Cane.gif" },
    "Rainbow Drop": { "img": "Rainbow-Drop.gif" },
    "Roast Beef": { "img": "Roast-Beef.gif" },
    "Pre-Chewed Gum": { "img": "Pre-Chewed-Gum.gif" },
    "Roast Beef Flavored Gum": { "img": "Roast-Beef-Flavored-Gum.gif" },
    "Semi-Lasting Gobstopper": { "img": "Semi-Lasting-Gobstopper.gif" },
    "Sweet Bomb": { "img": "Sweet-Bomb.gif" },
    "Blueberry Blast Jelly Beans": { "img": "Blueberry-Blast-Jelly-Beans.gif" },
    "Beef Mushroom Stew": { "img": "Beef-Mushroom-Stew.gif" },
    "Texas Fajita Soup": { "img": "Texas-Fajita-Soup.gif" },
    "Cream of Okra Soup": { "img": "Cream-of-Okra-Soup.gif" },
    "Garlic Salmon Bisque": { "img": "Garlic-Salmon-Bisque.gif" },
    "Beggars Bouillon": { "img": "Beggar%27s-Bouillon.gif" },
    "Fizzy Lifting Soda": { "img": "Fizzy-Lifting-Soda.gif" },
    "Wonkas Peppermint Spirits": { "img": "Wonka%27s-Peppermint-Spirits.gif" },
    "Altoids": { "img": "Altoids.gif" },
    "Junior Mints": { "img": "Junior-Mints.gif" },
    "Red Hots": { "img": "Red-Hots.gif" },
    "Crystal Pepsi": { "img": "Crystal-Pepsi.gif" },
    "Chocolate Vanilla Swirl Ice Cream": { "img": "Chocolate-Vanilla-Swirl-Ice-Cream.gif" },
    "Redder Hots": { "img": "Redder-Hots.gif" },
    "Gas Soaked Red Hots": { "img": "Gas-Soaked-Red-Hots.gif" },
    "Gummi Gorilla": { "img": "Gummi-Gorilla.gif" },
    "Gummi Peregrine Falcon": { "img": "Gummi-Peregrine-Falcon.gif" },
    "Gummi Raptor": { "img": "Gummi-Raptor.gif" },
    "Quantum Candy": { "img": "Quantum-Candy.gif" },
    "Gummi Spaghetti Monster": { "img": "Gummi-Spaghetti-Monster.gif" },
    "Fruit by the Furlong": { "img": "Fruit-by-the-Furlong.gif" },
    "Candy Cigarette": { "img": "Candy-Cigarette.gif" },
    "Pack of Candy Cigarettes": { "img": "Pack-of-Candy-Cigarettes.gif" },
    "Freeze-Packed Dippin Dots": { "img": "Freeze-Packed-Dippin-Dots.gif" },
    "Dippin Dots": { "img": "Dippin-Dots.gif" },
    "Military Rations": { "img": "Military-Rations.gif" },
    "Can of Whipped Cream": { "img": "Can-of-Whipped-Cream.gif" },
    "Faberge Cream Egg": { "img": "Faberge-Cream-Egg.gif" },
    "Apple Flavored Gum": { "img": "Apple-Flavored-Gum.gif" },
    "Cinnamon Flavored Gum": { "img": "Cinnamon-Flavored-Gum.gif" },
    "Dark Chocolate Wonka Bar": { "img": "Dark-Chocolate-Wonka-Bar.gif" },
    "Special Brownie": { "img": "Special-Brownie.gif" },
    "Bacon Blast Jelly Beans": { "img": "Bacon-Blast-Jelly-Beans.gif" },
    "Fizzy Falling Soda": { "img": "Fizzy-Falling-Soda.gif" },
    "Caulipop": { "img": "Caulipop.gif" },
    "Dalipop": { "img": "Dalipop.gif" },
    "Volleypop": { "img": "Volleypop.gif" },
    "Polypop": { "img": "Polypop.gif" },
    "Mountain Honeydew Melon": { "img": "Mountain-Honeydew-Melon.gif" },
    "Mountain Dew": { "img": "Mountain-Dew.gif" },
    "Salmon": { "img": "Salmon.gif" },
    "Catfish": { "img": "Catfish.gif" },
    "Fish Sticks": { "img": "Fish-Sticks.gif" },
    "Octopus": { "img": "Octopus.gif" },
    "Blowfish": { "img": "Blowfish.gif" },
    "Hobo Stew": { "img": "Hobo-Stew.gif" },
    "Beggars Brunch": { "img": "Beggars-Brunch.gif" },
    "Hangover Omelette": { "img": "Hangover-Omelette.gif" },
    "Stomach Parasite": { "img": "Stomach-Parasite.gif" },
    "Forest Shroom": { "img": "Forest-Shroom.gif" },
    "Garlic Clove": { "img": "Garlic-Clove.gif" },
    "Chili Pepper": { "img": "Chili-Pepper.gif" },
    "Okra": { "img": "Okra.gif" },
    "Gingerbread Bum": { "img": "Gingerbread-Bum.gif" },
    "Bernard Burger": { "img": "Bernard-Burger.gif" },
    "Flying Dutchman": { "img": "Flying-Dutchman.gif" },
    "Animal Style Fries": { "img": "Animal-Style-Fries.gif" },
    "Neapolitan Shake": { "img": "Neapolitan-Shake.gif" },
    "SARS Bar": { "img": "SARS-Bar.gif" },
    "Hobowarheads": { "img": "Hobowarheads.gif" },
    "Mop Rocks": { "img": "Mop-Rocks.gif" },
    "ICPeanut Butter Cup": { "img": "ICPeanut-Butter-Cup.gif" },
    "Sugarfree Gum": { "img": "Sugarfree-Gum.gif" },
    "Kit Rat Bar": { "img": "Kit-Rat-Bar.gif" },
    "Butlerfinger": { "img": "Butlerfinger.gif" },
    "Life Savers": { "img": "Life-Savers.gif" },
    "Pay Day": { "img": "Pay-Day.gif" },
    "Candycorn": { "img": "Candycorn.gif" },
    "Sourpatch Bums": { "img": "Sourpatch-Bums.gif" },
    "L&amp;Ls": { "img": "L&amp;Ls.gif" },
    "Apple Surprise": { "img": "Apple-Surprise.gif" },
    "Death Mints": { "img": "Death-Mints.gif" },
    "Blow-Up Pop": { "img": "Blow-Up-Pop.gif" },
    "Peppermint Burger Patties": { "img": "Peppermint-Burger-Patties.gif" },
    "Rock Candy": { "img": "Rock-Candy.gif" },
    "Walking Taco": { "img": "Walking-Taco.gif" },
    "Freedom Fries": { "img": "Freedom-Fries.gif" },
    "Jugger-Nut": { "img": "Jugger-Nut.gif" },
    "Pizza Del Mare": { "img": "Pizza-Del-Mare.gif" },
    "Bottle of Coke": { "img": "Bottle-of-Coke.gif" },
    "Brains": { "img": "Brains.gif" },
    "Death By Chocolate": { "img": "Death-By-Chocolate.gif" },
    "Spooky Biscuit": { "img": "Spooky-Biscuit.gif" },
    "Twozzlers": { "img": "Twozzlers.gif" },
    "Red Hot Chili Pepper": { "img": "Red-Hot-Chili-Pepper.gif" },
    "Longer-Lasting Gobstopper": { "img": "Longer-Lasting-Gobstopper.gif" },
    "Double Gorillas": { "img": "Double-Gorillas.gif" },
    "Double Falcons": { "img": "Double-Falcons.gif" },
    "Double Raptors": { "img": "Double-Raptors.gif" },
    "Triple Dipps": { "img": "Triple-Dipps.gif" },
    "Rainbow Balls": { "img": "Rainbow-Balls.gif" },
    "Wonka Quadra Candy Cane": { "img": "Wonka-Quadra-Candy-Cane.gif" },
};
